### ISSUE TITLE
cannot run awesome-ai-tutorials/Computer Vision /001 - unet/

### ISSUE THREAD

**Issue by brunotakara** [FrancoisPorcher/awesome-ai-tutorials#3]
I am getting this error:

```
-> [3122](https://file+.vscode-resource.vscode-cdn.net/d%3A/Bruno/archive/~/AppData/Roaming/Python/Python39/site-packages/torch/nn/functional.py:3122) return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)

RuntimeError: all elements of target should be between 0 and 1
```

When running the code for the 001 - unet on the Kaggle Dataset, I could not replicate your results because of this error, I tried normalizing the images by dividing the cv2.imread tensors for images and masks by 255.0 in class BrainMriDataset(Dataset). After that, the model begun training but it outputs poor predictions, do you have any idea how can I fix it?

**Comment by FrancoisPorcher** [comment]
Hi! This is because you should not normalise the target. The input image yes, you should divide by 255 to get pixel values between 0 and 1. However for the target, it is supposed to be an integer indicating the index of the class. 

For example if you have C classes to segment, your targets must be {0, 1, .., C-1}

**Comment by brunotakara** [comment]
Thanks! I divided the mask pixel values by 255.0 after augmentation and then the problem was solved! For some reason A.Normalize wasn't normalizing it. I also used A.Normalize(mean=0.0, std=1.0) instead of A.Normalize(p=1.0) so the values were normalized between 0 and 1
